gas:
  cp : 1004 # J/(kg*K)
  gamma: 1.4
  h_PR: 42.8 # J/kg

atmosphere:
  pressure_pa: 18750 # Pascal
  temperature_k: 216.7 # Kelvin
  mach: 0.9

# Engine_case : turbofanSS
# Engine_case : turboJet
Engine_case : MSturbofan

nozzleInlet:
  ideal: true
  pressure_ratio: 1.0
  temperature_ratio: 1.0

CombustionChamber:
  ideal: true
  pressure_ratio: 1.0
  efficiency: 1.0
  outletTemperature_k: 1670.0

Turbine:
  ideal: true
  efficiency: 1.0


afterburner: 
  ideal: true
  efficiency: 1.0
  pressure_ratio: 1.0
  outletTemperature_k: 2300.0

nozzleOutlet:
  ideal: true
  pressure_ratio: 1.0
  temperature_ratio: 1.0
  OutletPressure_pa: 18750

fan_nozzleOutlet:
  ideal: true
  pressure_ratio: 1.0
  temperature_ratio: 1.0
  OutletPressure_pa: 18750

Compressor:
  ideal: true
  pressure_ratio: 20
  efficiency: 1.0
  bypass_ratio: 1.5

Fan:
  ideal: false
  pressure_ratio: 2
  efficiency: 0.9
  class: Compressor


Fan_duct:
  ideal: true
  pressure_ratio: 1.0
  temperature_ratio: 1.0
  class: Nozzle


Mixer:
  Mach_in: 0.5